linters-settings:

  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 45
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - asasalint 
    - asciicheck 
    - bidichk 
    - bodyclose 
    - containedctx 
    - contextcheck 
    - cyclop 
    - decorder 
    - depguard 
    - dogsled 
    - dupl 
    - dupword
    - durationcheck 
    - errcheck 
    - errchkjson 
    - errname 
    - errorlint 
    - execinquery 
    - exhaustive 
    - exhaustruct 
    - exportloopref 
    - forbidigo 
    - forcetypeassert 
    - funlen 

    - gochecknoglobals 
    - gochecknoinits 
    - gocognit 

    - gocognit 
    - goconst 
    - gocritic 
    - gomnd 

    - gomoddirectives 
    - gomodguard 
    - goprintffuncname 
    - gosec 
    - gosimple 
    - govet 
    - grouper 
    - importas 
    - ineffassign 
    - interfacebloat 
    - ireturn 
    - lll 
    - loggercheck 
    - maintidx 
    - makezero 
    - misspell 
    - nakedret
    - nestif

    - nilerr 
    - nilnil 
    - nlreturn 
    - noctx 
    - nolintlint 
    - nonamedreturns 
    - nosprintfhostport 
    - paralleltest 
    - prealloc 
    - predeclared 
    - promlinter 
    - reassign 
    - revive 
    - rowserrcheck 
    - sqlclosecheck 
    - staticcheck 
    - stylecheck 
    - tagliatelle 
    - tenv 
    - testableexamples 
    - testpackage 
    - thelper 
    - tparallel 
    - typecheck 
    - unconvert 
    - unparam 
    - unused 
    - usestdlibvars 
    - varnamelen 
    - wastedassign 
    - whitespace 
    - wrapcheck 
    - wsl   

    - gochecknoglobals 
    - gochecknoinits 
    - gocritic 
    - gocyclo 
    - godot 
    - godox 
    - goerr113     

    - goconst 
    - gocyclo 
    - godot 
    - godox 
    - goerr113 
    - gofumpt     
  unsused:
    - structcheck
    - maligned 
    - deadcode
    - exhaustivestruct
    - interfacer
    - ifshort
    - golint
    - nosnakecase 
    - scopelint 
    - varcheck 
    - deadcode 
    - structcheck 
