Logger:
  DirLog: ./logs/
  FileSize: 10000000
  ApiShowRecords: 5
  KindType: "csv"

Proxy:
  Addr: ":8080"
  ShutdownTimeout: 10
  ReadHeaderTimeout: 30
  WriteTimeout: 30
  ReadTimeout: 30
  IdleTimeout: 60

Peers:
  - Name: test_backend_1
    Proto: http
    URI: 127.0.0.1:8040

  - Name: test_backend_2
    Proto: http
    URI: 127.0.0.1:8030

  - Name: test_backend_3
    Proto: http
    URI: 127.0.0.1:8020    

PeerCheckTimeAlive:  
  TimeCheck: 2
  WaitTimeCheck: 2
