// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/proxy/peer/peer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	peer "vbalancer/internal/proxy/peer"
	vlog "vbalancer/internal/vlog"

	gomock "github.com/golang/mock/gomock"
)

// MockIPeer is a mock of IPeer interface.
type MockIPeer struct {
	ctrl     *gomock.Controller
	recorder *MockIPeerMockRecorder
}

// MockIPeerMockRecorder is the mock recorder for MockIPeer.
type MockIPeerMockRecorder struct {
	mock *MockIPeer
}

// NewMockIPeer creates a new mock instance.
func NewMockIPeer(ctrl *gomock.Controller) *MockIPeer {
	mock := &MockIPeer{ctrl: ctrl}
	mock.recorder = &MockIPeerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPeer) EXPECT() *MockIPeerMockRecorder {
	return m.recorder
}

// CheckIsAlive mocks base method.
func (m *MockIPeer) CheckIsAlive(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckIsAlive", arg0)
}

// CheckIsAlive indicates an expected call of CheckIsAlive.
func (mr *MockIPeerMockRecorder) CheckIsAlive(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsAlive", reflect.TypeOf((*MockIPeer)(nil).CheckIsAlive), arg0)
}

// GetURI mocks base method.
func (m *MockIPeer) GetURI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURI")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetURI indicates an expected call of GetURI.
func (mr *MockIPeerMockRecorder) GetURI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURI", reflect.TypeOf((*MockIPeer)(nil).GetURI))
}

// IsAlive mocks base method.
func (m *MockIPeer) IsAlive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAlive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAlive indicates an expected call of IsAlive.
func (mr *MockIPeerMockRecorder) IsAlive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAlive", reflect.TypeOf((*MockIPeer)(nil).IsAlive))
}

// SetCheckTimeAlive mocks base method.
func (m *MockIPeer) SetCheckTimeAlive(arg0 *peer.CheckTimeAlive) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCheckTimeAlive", arg0)
}

// SetCheckTimeAlive indicates an expected call of SetCheckTimeAlive.
func (mr *MockIPeerMockRecorder) SetCheckTimeAlive(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCheckTimeAlive", reflect.TypeOf((*MockIPeer)(nil).SetCheckTimeAlive), arg0)
}

// SetLogger mocks base method.
func (m *MockIPeer) SetLogger(arg0 vlog.ILog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", arg0)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockIPeerMockRecorder) SetLogger(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockIPeer)(nil).SetLogger), arg0)
}
