proxy:
  defaultPort: 8080
  clientDeadLineTimeSec: 10
  destinationHostTimeoutMs: 1
  destinationHostDeadLineSec: 10
  shutdownTimeoutSeconds: 10
  connectionSemaphore: 500
  countDialAttemptsToPeer: 30

peers:

  - name: test_backend_1
    uri: 127.0.0.1:8020

  - name: test_backend_2
    uri: 127.0.0.1:8030

  - name: test_backend_3
    uri: 127.0.0.1:8040

  - name: test_backend_4
    uri: 127.0.0.1:8050    

  - name: test_backend_5
    uri: 127.0.0.1:8060    

  - name: test_backend_6
    uri: 127.0.0.1:8070 

  - name: test_backend_7
    uri: 127.0.0.1:8090    

logger:
  dirLog: ./logs/
  fileSize: 10000000
  apiShowRecords: 5