proxy:

  port: 8080
  clientDeadLineTime: 2s
  peerConnectionTimeout: 1s
  maxCountConnection: 100

  rules:
    blacklist:
      cacheDurationToEvict: 1h
      remoteIp:
        - 127.0.0.5

  peers:
    timeToEvictNotResponsePeers: 60s
    list:
      - name: test_backend_1
        uri: 127.0.0.1:6010
      - name: test_backend_2
        uri: 127.0.0.1:6011

logger:
  dirLog: ./logs/
  fileSizeInMb: 10
  apiShowRecords: 50