logger:
  DirLog: ./logs/
  FileSize: 10000000
  ApiShowRecords: 5
  KindType: "csv"

proxy:
  DefaultPort: 8080
  TimeDeadLineMS: 200
  ShutdownTimeout: 10
  
peers:
  - Name: test_backend_1
    Proto: http
    URI: 127.0.0.1:8040

  - Name: test_backend_2
    Proto: http
    URI: 127.0.0.1:8030

  - Name: test_backend_3
    Proto: http
    URI: 127.0.0.1:8020    

peerCheckTimeAlive:  
  TimeCheck: 2
  WaitTimeCheck: 2
