proxy:
  defaultPort: 8080
  clientDeadLineTimeSec: 10
  destinationHostTimeoutMs: 1
  destinationHostDeadLineSec: 10
  shutdownTimeoutSeconds: 10
  connectionSemaphore: 300

peers:
  - name: test_backend_1
    proto: http
    uri: 127.0.0.1:8040

  - name: test_backend_2
    proto: http
    uri: 127.0.0.1:8030

  - name: test_backend_3
    proto: http
    uri: 127.0.0.1:8020    

logger:
  dirLog: ./logs/
  fileSize: 10000000
  apiShowRecords: 5