proxy:
  defaultPort: 8080
  clientDeadLineTime: 1s
  destinationHostTimeout: 60s
  destinationHostDeadLine: 1s
  maxCountConnection: 1000
  countDialAttemptsToPeer: 30

peers:

  - name: test_backend_1
    uri: 127.0.0.1:8081

  - name: test_backend_2
    uri: 127.0.0.1:8082

logger:
  dirLog: ./logs/
  fileSize: 10000000
  apiShowRecords: 5

rules:
  blacklist: 
    remoteIp: 
      - 127.0.0.5
      - 192.168.1.40

