name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go: [ '1.19' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Download Deps
        run: go mod download

      - name: Check go.mod
        run: |
          go mod tidy -v
          git diff --name-only --exit-code go.mod || ( git diff && echo "Run go tidy to update go.mod" && false )

      - name: Test All
        run: go test -short ./...

      - name: Linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
          golangci-lint --version
          golangci-lint run -v ./...

      - name: Build All
        run: |
          make build

